### ISSUE TITLE
Fuckin Hilarious

### ISSUE THREAD

**Issue by TyDevX** [KookerFoxYT/GPTFlixelPlatformer#1]
Nigga had to use ChatGPT because he doesn't know how to code 💀

**Comment by KookerFoxYT** [comment]
bro I just wanted to see if gpt can make a game based on have
and besides I only use haxe for fnf

**Comment by TyDevX** [comment]
💀 Still all of "your" haxe code is skidded from other fnf engines

**Comment by KookerFoxYT** [comment]
> 💀 Still all of "your" haxe code is skidded from other fnf engines

get the fuck out

**Comment by KookerFoxYT** [comment]
almost everyone else doesn't care anyways
